version: '3'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: konzek
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    container_name: my_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  your_other_service:
    image: ghcr.io/tugberkurganci/app:main
    container_name: 54bb83c41884a5b531293da4047fb3979e117c45b1339d6603ac6a63a664758d
    restart: always
    ports:
      - "8080:8080"
  
    
