version: '3'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: konzek
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    container_name: my_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  your_other_service:
    image: ghcr.io/tugberkurganci/app:main
    container_name: d84aa0a90db0c3da8c61897be346adefab70d81c03f5c62b576de249765e4e54
    restart: always
    ports:
      - "8080:8080"
      - "2222:2222"
  
    
