version: '3'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: konzek
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    container_name: my_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  your_other_service:
    image: ghcr.io/tugberkurganci/app:main
    container_name: ad7b370c7560dca7d54ab107dbcb92ff8123065e95a35b09d999e9c3b07baaf1
    restart: always
    ports:
      - "8080:8080"
      - "2222:2222"
  
    
