version: '3'

services:
  postgres:
    image: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: konzek
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus
    container_name: my_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  your_other_service:
    image: ghcr.io/tugberkurganci/app:main
    container_name: 187615ee6a2796cd0a3c30b2a871c00544b68cb7ade15f2377eee8277ac183ba
    restart: always
    ports:
      - "8080:8080"
      - "2222:2222"
  
    
